# Generated by Django 4.1.7 on 2023-03-12 11:07

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=500, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('short_description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Short Description')),
                ('logo', models.ImageField(default='images/default.jpg', upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('message', models.TextField(max_length=500, verbose_name='Message')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('visit', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Page Views',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Bank', 'Bank'), ('NGO', 'NGO'), ('Finance', 'Finance'), ('Education', 'Education'), ('Hospitality', 'Hospitality'), ('IT', 'IT'), ('Engineering', 'Engineering'), ('Transportation', 'Transportation'), ('Legal-Service', 'Legal Service'), ('Health', 'Health'), ('Manufacturing', 'Manufacturing'), ('Creative-Art', 'Creative Art'), ('Skill-Work', 'Skill Work')], max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Sectors',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=500, unique=True)),
                ('experience', models.CharField(choices=[('Entry Level', 'Entry Level'), ('Junior Level', 'Junior Level'), ('Senior Level', 'Senior Level'), ('Managerial Level', 'Managerial Level'), ('Executive', 'Executive'), ('Senior Executive', 'Senior Executive')], max_length=20, verbose_name='Experience')),
                ('job_type', models.CharField(choices=[('Contract', 'Contract'), ('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Internship', 'Internship'), ('Volunteer', 'Volunteer'), ('Temporary', 'Temporary'), ('Other', 'Other')], max_length=20, verbose_name='Job Type')),
                ('work_mode', models.CharField(choices=[('On-site', 'On-site'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid')], max_length=20, verbose_name='Work Mode')),
                ('region', models.CharField(choices=[('Addis-Ababa', 'Addis Ababa'), ('Dre-Dawa', 'Dre Dawa'), ('Afar', 'Afar'), ('Amhara', 'Amhara'), ('Tigray', 'Tigray'), ('Benishangul-Gumuz', 'Benishangul Gumuz'), ('Gambela', 'Gambela'), ('Harari', 'Harari'), ('Oromia', 'Oromia'), ('Sidama', 'Sidama'), ('Somali', 'Somali'), ('SNNPR', 'SNNPR'), ('SWEP', 'SWEP'), ('Unspecified', 'Unspecified')], max_length=20)),
                ('quantity_required', models.IntegerField(blank=True, null=True, verbose_name='Quanity Required')),
                ('how_to_apply', ckeditor.fields.RichTextField(verbose_name='How To Apply')),
                ('deadline', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.company')),
                ('sectors', models.ManyToManyField(to='main.sector')),
            ],
        ),
    ]
